name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ppcm-server . --file Dockerfile --tag ppcmc-server:latest

      - name: Login to Docker registry
        run: docker login -u ${{secrets.DOCKER_REGISTRY_USERNAME}} -p ${{secrets.DOCKER_REGISTRY_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}

      - name: Tag the Docker image
        run: docker image tag ppcm-server ${{secrets.DOCKER_REGISTRY}}/ppmc/ppcm-server:latest

      - name: Push the Docker image to registry
        run: docker push ${{secrets.DOCKER_REGISTRY}}/ppmc/ppcm-server:latest
